import { MenuItem } from "primereact/menuitem";
import { ReviewType } from "./types.tsx";
import { SongOrAlbumEnum } from "./enums.tsx";

export const TABS_MENU: MenuItem[] = [
  { label: "Newest", icon: "pi pi-clock" },
  { label: "All Reviews", icon: "pi pi-list-check" },
  { label: "Songs", icon: "pi pi-headphones" },
  { label: "Albums", icon: "pi pi-book" },
  { label: "Artists", icon: "pi pi-star-fill" },
  { label: "Profile", icon: "pi pi-user" },
];

export const CAT_IMAGE: string = import.meta.env.VITE_CAT_IMAGE;

export const MOCK_REVIEWS: ReviewType[] = [
  {
    id: 1,
    name: "Back in Black",
    image: CAT_IMAGE,
    date: "2-8-2024",
    rating: 1,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "albumaddict",
  },
  {
    id: 2,
    name: "Billie Jean",
    image: CAT_IMAGE,
    date: "27-3-2025",
    rating: 1,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "groove_guru",
  },
  {
    id: 3,
    name: "Like a Rolling Stone",
    image: CAT_IMAGE,
    date: "10-11-2024",
    rating: 3,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "melody_mike",
  },
  {
    id: 4,
    name: "Bohemian Rhapsody",
    image: CAT_IMAGE,
    date: "30-7-2025",
    rating: 5,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "groove_guru",
  },
  {
    id: 5,
    name: "Wish You Were Here",
    image: CAT_IMAGE,
    date: "29-6-2025",
    rating: 4,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "jbockal",
  },
  {
    id: 6,
    name: "Hotel California",
    image: CAT_IMAGE,
    date: "4-5-2024",
    rating: 1,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "soundwave_sam",
  },
  {
    id: 7,
    name: "Wish You Were Here",
    image: CAT_IMAGE,
    date: "27-12-2024",
    rating: 4,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "vinylvicky",
  },
  {
    id: 8,
    name: "Hotel California",
    image: CAT_IMAGE,
    date: "19-3-2025",
    rating: 4,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "musicman22",
  },
  {
    id: 9,
    name: "Stairway to Heaven",
    image: CAT_IMAGE,
    date: "12-2-2025",
    rating: 2,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "beatmeister",
  },
  {
    id: 10,
    name: "Purple Rain",
    image: CAT_IMAGE,
    date: "28-10-2024",
    rating: 4,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "jbockal",
  },
  {
    id: 11,
    name: "Bohemian Rhapsody",
    image: CAT_IMAGE,
    date: "17-11-2025",
    rating: 1,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "rocknroll_ralf",
  },
  {
    id: 12,
    name: "Wish You Were Here",
    image: CAT_IMAGE,
    date: "24-6-2024",
    rating: 1,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "albumaddict",
  },
  {
    id: 13,
    name: "Wish You Were Here",
    image: CAT_IMAGE,
    date: "21-7-2025",
    rating: 5,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "beatmeister",
  },
  {
    id: 14,
    name: "Smells Like Teen Spirit",
    image: CAT_IMAGE,
    date: "15-4-2024",
    rating: 1,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "groove_guru",
  },
  {
    id: 15,
    name: "Purple Rain",
    image: CAT_IMAGE,
    date: "23-8-2025",
    rating: 3,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "soundwave_sam",
  },
  {
    id: 16,
    name: "Like a Rolling Stone",
    image: CAT_IMAGE,
    date: "17-4-2025",
    rating: 4,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "tuned_in_tam",
  },
  {
    id: 17,
    name: "Hotel California",
    image: CAT_IMAGE,
    date: "9-7-2024",
    rating: 3,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "musicman22",
  },
  {
    id: 18,
    name: "Wish You Were Here",
    image: CAT_IMAGE,
    date: "11-9-2025",
    rating: 2,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "groove_guru",
  },
  {
    id: 19,
    name: "Hotel California",
    image: CAT_IMAGE,
    date: "25-8-2025",
    rating: 3,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "rocknroll_ralf",
  },
  {
    id: 20,
    name: "Purple Rain",
    image: CAT_IMAGE,
    date: "16-5-2025",
    rating: 2,
    songOrAlbum: SongOrAlbumEnum.SONG,
    username: "rocknroll_ralf",
  },
];
