spring.datasource.url=jdbc:postgresql://localhost:5432/music-reviews-portal-db
spring.datasource.username=jbockal
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# tells Hibernate to create/update tables on startup:
spring.jpa.hibernate.ddl-auto=update

# logs SQL statements:
spring.jpa.show-sql=true