spring.datasource.url=jdbc:postgresql://localhost:5432/music-reviews-portal-db
spring.datasource.username=jbockal
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
server.servlet.context-path=/api
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
logging.level.org.springframework.security=DEBUG

# allow up to 20MB per file and 25MB total request
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=25MB


# tells Hibernate to create/update tables on startup:
spring.jpa.hibernate.ddl-auto=update

# logs SQL statements:
spring.jpa.show-sql=true